export default {
  products: [
    {
      _id: "1",
      name: "Men African Prints",
      category: "African Prints",
      image: "/images/Print2.jpg",
      price: 89.99,
      brand: "Liddel Trend",
      rating: 4.5,
      numReviews: 150,
      countInStock: 20,
    },
    {
      _id: "2",
      name: "Adepa Local Rice",
      category: "Local Rice",
      image: "/images/Adepa1.jpg",
      price: 13.59,
      brand: "Trolley Market",
      rating: 5.0,
      numReviews: 250,
      countInStock: 20000,
    },
    {
      _id: "3",
      name: "Ladies Bag",
      category: "Bags & Totes",
      image: "/images/Bag1.jpg",
      price: 39.99,
      brand: "Liddel Trend",
      rating: 4.2,
      numReviews: 150,
      countInStock: 9,
    },
    {
      _id: "4",
      name: "Men African Wear",
      category: "African Prints",
      image: "/images/print6.jpg",
      price: 129.99,
      brand: "Liddel Trend",
      rating: 4.0,
      numReviews: 60,
      countInStock: 5,
    },
    {
      _id: "5",
      name: "Wedding Decor",
      category: "Wedding",
      image: "/images/Wedd8.jpg",
      price: 2599.99,
      brand: "Liddel Trend",
      rating: 3.5,
      numReviews: 50,
      countInStock: 1,
    },
    {
      _id: "6",
      name: "Wedding Decor",
      category: "Wedding",
      image: "/images/Wedd10.jpg",
      price: 2399.99,
      brand: "Liddel Trend",
      rating: 4.1,
      numReviews: 70,
      countInStock: 2,
    },
    {
      _id: "7",
      name: "Wedding Decor",
      category: "Wedding",
      image: "/images/Wedd15.jpg",
      price: 2799.99,
      brand: "Liddel Trend",
      rating: 4.0,
      numReviews: 50,
      countInStock: 1,
    },
    {
      _id: "8",
      name: "Aseda Local Rice",
      category: "Local Rice",
      image: "/images/AsedaFront.jpg",
      price: 28.99,
      brand: "Trolley Market Group",
      rating: 4.5,
      numReviews: 150,
      countInStock: 30000,
    },
    {
      _id: "9",
      name: "Men African Prints",
      category: "African Prints",
      image: "/images/Print5.jpg",
      price: 75.99,
      brand: "Liddel Trend",
      rating: 4.5,
      numReviews: 100,
      countInStock: 25,
    },
  ],
};
